seperate OjoTrack and argv handling
FreaxMATE/Ojo pull request #14
Opened 2019-12-02 18:08 UTC by FreaxMATE

This seperates OjoTrack to ojo-track.c (with ojo-track.h) and adds the ability to handle command line arguments. As follows you can now right click on multiple media files and open with ojo from your favorite file manager.

2019-12-02 18:10 UTC, FreaxMATE commented on src/ojo-player.c
> +      // g_free(list->data) ; TODO: free uris; causes errors
This causes some troubles (freeing the uri strings (gpointer) returned by file manager)

2019-12-06 13:31 UTC, mbkma requested changes
Title is "unknown" when opening from right-click menu for me. The uri strings should be freed before we merge this. Otherwise it works.

2019-12-07 18:46 UTC, FreaxMATE commented on src/ojo-player.c
> +      // g_free(list->data) ; TODO: free uris; causes errors
solved in 56e5ba5

2019-12-07 20:11 UTC, FreaxMATE commented
Everything should be fine now.

2019-12-07 20:40 UTC, mbkma commented
In this branch I get an error when opening ~20 music files. gdb:
```
.
.
.
WARNING: ojo_player_tracks_initialize() in ojo-player.c: failed to fetch metadata
WARNING: ojo_player_tracks_initialize() in ojo-player.c: failed to fetch metadata
WARNING: ojo_player_tracks_initialize() in ojo-player.c: failed to fetch metadata
WARNING: ojo_player_tracks_initialize() in ojo-player.c: failed to fetch metadata
WARNING: ojo_player_tracks_i^C
Thread 1 "ojo" received signal SIGINT, Interrupt.
__GI___libc_write (nbytes=82, buf=0x55555555d138, fd=2)
    at ../sysdeps/unix/sysv/linux/write.c:26
26	../sysdeps/unix/sysv/linux/write.c: No such file or directory.
(gdb) backtrace
#0  0x00007ffff7251537 in __GI___libc_write
    (nbytes=82, buf=0x55555555d138, fd=2)
    at ../sysdeps/unix/sysv/linux/write.c:26
#1  0x00007ffff7251537 in __GI___libc_write
    (fd=2, buf=0x55555555d138, nbytes=82)
    at ../sysdeps/unix/sysv/linux/write.c:24
#2  0x00007ffff71e23bd in _IO_new_file_write
    (f=0x7ffff7323680 <_IO_2_1_stderr_>, data=0x55555555d138, n=82)
    at fileops.c:1183
#3  0x00007ffff71e175f in new_do_write
    (fp=fp@entry=0x7ffff7323680 <_IO_2_1_stderr_>, data=data@entry=0x55555555d138 "WARNING: ojo_player_tracks_initialize() in ojo-player.c: failed to fetch metadata\n", to_do=to_do@entry=82) at libioP.h:839
#4  0x00007ffff71e2aee in _IO_new_file_xsputn
    (n=82, data=<optimized out>, f=0x7ffff7323680 <_IO_2_1_stderr_>)
    at fileops.c:1262
#5  0x00007ffff71e2aee in _IO_new_file_xsputn
    (f=0x7ffff7323680 <_IO_2_1_stderr_>, data=<optimized out>, n=82)
    at fileops.c:1204
#6  0x00007ffff71d7ae8 in __GI__IO_fwrite
    (buf=0x55555555d138, size=1, count=82, fp=0x7ffff7323680 <_IO_2_1_stderr_>)
    at libioP.h:839
#7  0x0000555555559cd7 in ojo_player_tracks_initialize
```

2019-12-09 19:03 UTC, mbkma approved these changes
Its fine.

2019-12-09 20:58 UTC, merged